import streamlit as st
from io import BytesIO
from html import escape

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.units import inch


# ============================================================
# ui_components.py
# Reusable visual cards, reports, share boxes, PDF reports
# ============================================================


def set_page(page_name):
    st.session_state.page = page_name
    st.rerun()


def render_risk_card(title, probability, band, icon, description):
    if band == "Low":
        card_class = "risk-low"
    elif band == "Moderate":
        card_class = "risk-moderate"
    else:
        card_class = "risk-high"

    st.markdown(
        f"""
        <div class="{card_class}">
            <div class="risk-label">{icon} {title}</div>
            <div class="big-score">{probability:.1%}</div>
            <div style="font-size:24px; font-weight:900; color:#0f172a;">{band} Risk Awareness</div>
            <p class="small-muted">{description}</p>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_factor_cards(factors):
    st.markdown(
        '<div class="section-header">⚠️ Key Risk Signals</div>',
        unsafe_allow_html=True,
    )

    for factor in factors:
        st.markdown(
            f"""
            <div class="factor-card">
                <strong>{factor}</strong>
            </div>
            """,
            unsafe_allow_html=True,
        )


def build_share_text(
    personal_band=None,
    personal_probability=None,
    state_name=None,
    state_band=None,
    state_probability=None,
    combined_level=None,
):
    lines = ["🩺 Chronic Risk Watch Summary", ""]

    if personal_band is not None and personal_probability is not None:
        lines.append(
            f"👤 Personal risk-awareness level: {personal_band} ({personal_probability:.1%})"
        )

    if state_name is not None and state_band is not None and state_probability is not None:
        lines.append(f"🗺️ State risk context for {state_name}: {state_band}")
        lines.append(f"📊 Model High-Risk Score: {state_probability * 100:.1f} / 100")

    if combined_level is not None:
        lines.append(f"🔗 Combined awareness level: {combined_level}")

    lines.append("")

    if state_name is not None:
        lines.append(
            "Note: The state score is a model classification signal, not a real-world disease probability."
        )

    lines.append("This is for educational awareness only, not medical diagnosis.")
    lines.append("Built with public health data + machine learning.")

    return "\n".join(lines)


def create_downloadable_report(
    report_title,
    personal_band=None,
    personal_probability=None,
    state_name=None,
    state_band=None,
    state_probability=None,
    combined_level=None,
    factors=None,
):
    lines = [
        report_title,
        "=" * len(report_title),
        "",
        "Generated by Chronic Risk Watch",
        "",
    ]

    if personal_band is not None:
        lines.extend(
            [
                "PERSONAL RISK-AWARENESS RESULT",
                "-" * 38,
                f"Risk-awareness level: {personal_band}",
                f"Personal Risk-Awareness Score: {personal_probability * 100:.1f} / 100",
                "Note: This score is an educational awareness signal, not a medical diagnosis.",
                "",
            ]
        )

    if state_name is not None:
        lines.extend(
            [
                "STATE RISK CONTEXT",
                "-" * 38,
                f"State: {state_name}",
                f"State risk signal: {state_band}",
                f"Model High-Risk Score: {state_probability * 100:.1f} / 100",
                "Note: This score is a model classification signal, not a real-world disease probability.",
                "",
            ]
        )

    if combined_level is not None:
        lines.extend(
            [
                "COMBINED AWARENESS",
                "-" * 38,
                f"Combined awareness level: {combined_level}",
                "",
            ]
        )

    if factors:
        lines.append("KEY RISK SIGNALS")
        lines.append("-" * 38)

        for factor in factors:
            lines.append(f"- {factor}")

        lines.append("")

    lines.extend(
        [
            "SUGGESTED PREVENTION FOCUS",
            "-" * 38,
            "- Use this result as awareness, not diagnosis.",
            "- Consider routine screening discussions with a healthcare professional.",
            "- Monitor blood pressure, cholesterol, BMI, and physical activity.",
            "- Public-health context does not determine individual health outcomes.",
            "",
            "DISCLAIMER",
            "-" * 38,
            "This report is for educational risk awareness only. It is not a medical diagnosis and should not replace advice from a healthcare professional.",
        ]
    )

    return "\n".join(lines)


def create_pdf_report(report_text):
    """
    Convert plain report text into a simple downloadable PDF.
    """
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        alignment=TA_LEFT,
        spaceAfter=14,
    )

    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        spaceBefore=12,
        spaceAfter=6,
    )

    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10.5,
        leading=14,
        spaceAfter=5,
    )

    story = []
    lines = report_text.split("\n")

    for i, line in enumerate(lines):
        clean_line = line.strip()

        if not clean_line:
            story.append(Spacer(1, 0.08 * inch))
            continue

        # Escape special characters so ReportLab does not treat them as HTML tags.
        safe_line = escape(clean_line)

        # First line is report title.
        if i == 0:
            story.append(Paragraph(safe_line, title_style))
            continue

        # Skip underline separator lines.
        if set(clean_line) in [{"="}, {"-"}]:
            continue

        # Section headings are uppercase lines.
        if clean_line.isupper() and len(clean_line) > 3:
            story.append(Paragraph(safe_line, heading_style))
            continue

        # Bullet lines.
        if clean_line.startswith("- "):
            safe_bullet = escape(clean_line[2:])
            story.append(Paragraph(f"• {safe_bullet}", body_style))
            continue

        story.append(Paragraph(safe_line, body_style))

    doc.build(story)

    pdf_bytes = buffer.getvalue()
    buffer.close()

    return pdf_bytes


def render_share_box(share_text):
    st.markdown(
        """
        <div class="share-card">
            <h3>📤 Share this with a friend</h3>
            <p>
            Copy the summary below or download your mini report.
            This makes the app easy to share for portfolio demos, class presentations, and friends.
            </p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.text_area(
        "Copyable share summary",
        share_text,
        height=150,
    )


def render_guidance_card(guidance):
    st.markdown(
        f"""
        <div class="glass-card">
            <h3 style="margin-top:0;">🧭 What this means for you</h3>
            <h4 style="color:#0f172a;">{guidance["title"]}</h4>
            <p style="font-size:16px; color:#475569; line-height:1.7;">
                {guidance["meaning"]}
            </p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown("### ✅ Helpful next steps")

    for step in guidance["next_steps"]:
        st.markdown(
            f"""
            <div class="factor-card">
                <strong>{step}</strong>
            </div>
            """,
            unsafe_allow_html=True,
        )

    st.markdown("### 🚫 What not to assume")

    for item in guidance["dont_assume"]:
        st.markdown(
            f"""
            <div class="factor-card">
                <strong>{item}</strong>
            </div>
            """,
            unsafe_allow_html=True,
        )


def render_disclaimer_card():
    st.markdown(
        """
        <div class="warning-card">
            This app is for educational risk awareness only. It is not a medical diagnosis and should not replace advice from a healthcare professional.
        </div>
        """,
        unsafe_allow_html=True,
    )